version: '3'

services:

  backend-db:
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    command: postgres -c log_statement=all

  backend:
    build: ./back/lab4
    command: java -jar weblab4.jar
    restart: unless-stopped
    environment:
#      - 'PG_DB_URL=jdbc:postgresql://backend-db:5432/postgres'
#      - 'PG_DB_USERNAME=postgres'
#      - 'PG_DB_PASSWORD=postgres'
      - 'SERVER_PORT=8080'
    depends_on:
      - backend-db